### ISSUE TITLE
TV Shows are combining but I still see 2 posters on the Main page

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [danieladov/jellyfin-plugin-mergeversions#12]
I have a 1080p and 4K version, when I go into the shows episode list both are combined but on the main page you still can see the 2 different versions of the shows main poster.

<img width="279" alt="double2" src="https://user-images.githubusercontent.com/53286741/107575563-a49df500-6bb5-11eb-845d-ab98ad9a76cf.PNG">

**Comment by danieladov** [comment]
You need to enable this option under the library settings
![Captura](https://user-images.githubusercontent.com/29411250/107582758-45ae9f00-6bfa-11eb-95f6-f3a3a3ee2413.PNG)

**Comment by Cookie-Monster-Coder** [comment]
That worked, Thank you! When I set up the library, I thought the plugin would automatically take care of it and didn't think twice.

**Comment by geebru** [comment]
I don't think this needs to be re-opened yet (I'm not putting it past user error), but since there's no discussion page. I found this as my episodes are merging perfectly, I get a version selector as I'd expect, but I can't for the life of me get the show to merge.

<img width="412" height="351" alt="Arcane showing 2 identical entries" src="https://github.com/user-attachments/assets/5ab5e358-18c8-47e3-80ef-522e7abd47f1" />

<img width="812" height="171" alt="Jellyfin setting showing "Automatically merge shows across folders as enabled" src="https://github.com/user-attachments/assets/03453ee6-cc19-4ca8-81f8-7113732b2d1d" />

I've got Auto Merge Across Folders enabled on _both_ the TV Shows and TV Shows (UHD) libraries, but even after multiple library scans, I can't get it to combine them. Any ideas?
